name: Docker Build and Push

on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract yt-dlp version from requirements.txt
        id: ytdlp_version
        run: |
          YTDLP_VERSION=$(grep -E '^yt-dlp==' requirements.txt | cut -d'=' -f3)
          echo "YTDLP_VERSION=${YTDLP_VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            zachfleeman/yt-dlp-flask:latest
            zachfleeman/yt-dlp-flask:${{ env.YTDLP_VERSION }}
